### 계정 등록
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "userId": "account2131",
  "password": "1234",
  "name": "user1",
  "email": "account@account"
}

### 계정 등록
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "userId": "admin",
  "password": "1234",
  "name": "admin",
  "email": "admin@admi"
}

### 전체 계정 조회
GET http://localhost:8080/api/users

### 계정 조회
GET http://localhost:8080/api/users/21/info
Content-Type: application/json

### 아이디 비밀번호 조회
GET http://localhost:8080/api/users/admin/auth

### 계정 수정
PUT http://localhost:8080/api/users/1
Content-Type: application/json

{
  "password": "",
  "status": "ACTIVE",
  "role": "ADMIN"
}

### 계정 삭제
DELETE http://localhost:8080/api/users/4