### 계정 등록
POST http://localhost:8080/api/account/users
Content-Type: application/json

{
  "userId": "account2131",
  "password": "1234",
  "name": "user1",
  "email": "account@account"
}

### 계정 등록
POST http://localhost:8080/api/account/users
Content-Type: application/json

{
  "userId": "admin",
  "password": "1234",
  "name": "admin",
  "email": "admin@admi"
}

### 계정 등록
POST http://localhost:8080/api/account/oauth/users
Content-Type: application/json

{
  "oauthId": "test-oauthId",
  "type": "payco",
  "name": "pc",
  "email": "email@sdas"
}

### 전체 계정 조회
GET http://localhost:8080/api/account/users

### 계정 조회
GET http://localhost:8080/api/account/users/17/info?type=direct
Content-Type: application/json

### 로그인 아이디 비밀번호 조회
GET http://localhost:8080/api/account/users/admin/credentials

### OAuth 로그인 아이디 비밀번호 조회
GET http://localhost:8080/api/account/oauth/users/test-oauthId

### 계정 수정
PUT http://localhost:8080/api/account/users/2
Content-Type: application/json

{
  "status": "ACTIVE"
}

### 계정 삭제
DELETE http://localhost:8080/api/account/users/2