### 유저 등록
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "userId": "account",
  "password": "1234",
  "name": "user1",
  "email": "account@account"
}

### 유저 등록
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "userId": "admin",
  "password": "1234",
  "name": "ACTIVE",
  "email": "admin@admi"
}

### 유저 조회
GET http://localhost:8080/api/users/admin/info
Content-Type: application/json

### 아이디 비밀번호 조회
GET http://localhost:8080/api/users/admin/auth

### 유저 수정
PUT http://localhost:8080/api/users/admin
Content-Type: application/json

{
  "password": "tt",
  "status": "ACTIVE",
  "role": "USER"
}

### 유저 삭제
DELETE http://localhost:8080/api/users/admin