eureka:
  client:
    enabled: false
    register-with-eureka: 'true'
    fetch-registry: 'true'
    service-url:
      defaultZone: http://192.168.0.23:8761/eureka
  instance:
    prefer-ip-address: 'true'


spring:
  jpa:
    open-in-view: 'false'
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        use_sql_comments: 'true'
        format_sql: 'true'
        show_sql: 'true'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: '2000'
      connection-test-query: SELECT 1
  application:
    name: account-service
  profiles:
    active: db

