### 계정 등록
POST http://localhost:8080/api/account/users
Content-Type: application/json

{
  "loginId": "qaw1",
  "password": "1234",
  "name": "미정",
  "email": "mj@account"
}
### Direct 계정 등록
POST http://localhost:8080/api/account/users
Content-Type: application/json

{
  "loginId": "admin1",
  "password": "1234",
  "name": "admin",
  "email": "admin@admi"
}
### Oauth 계정 등록
POST http://localhost:8080/api/account/oauth/users
Content-Type: application/json

{
  "oauthId": "oauthtest10",
  "oauthType": "payco",
  "name": "opc",
  "email": "email@sdas"
}

### 전체 계정 조회
GET http://localhost:8080/api/account/users

### 계정 조회
GET http://localhost:8080/api/account/users/4
Content-Type: application/json

### 로그인 아이디 비밀번호 조회
GET http://localhost:8080/api/account/users/admin/credentials

### OAuth 조회
GET http://localhost:8080/api/account/oauth/users/oauthtest1

### 계정 수정
PUT http://localhost:8080/api/account/users/3
Content-Type: application/json

{
  "name": "qaw",
  "phone": "010-1122-3334",
  "email": "email@aiotone.live",
  "role": "ADMIN"
}

### 비밀번호 수정
PUT http://localhost:8080/api/account/users/3/password
Content-Type: application/json

{
  "password": "asdf"
}

### 계정 삭제
DELETE http://localhost:8080/api/account/users/3